### PR TITLE
Fixes "ReferenceError: hostClients is not defined" issue

### PR DESCRIPTION
**Pull request by jplock**
This fix was created by @admanb, I'm just creating a new pull request which only contains the fix for this one issue.

### CODE REVIEW

**Comment by ghost** [comment]
Would be nice if this issue could be fixed!!!

**Comment by Rundfunk** [comment]
I also encountered this error. It would be great if the commit can be accepted!

**Comment by BrianTheCoder** [comment]
I just downloaded the package and started using it, right now this error is holding me up seeing as I get it everytime I try to send an email. Any ETA for this to be fixed?

**Comment by admanb** [comment]
I recommend everyone push the library out of their packages directory and into a /lib folder, then make the change yourself. It is unlikely that this will be fixed any time soon given the lack of activity from the owner.

**Comment by BrianTheCoder** [comment]
is this package abandonware? if so, probably best to not use it in your app at all. Are there other alternatives?

**Comment by admanb** [comment]
Keep in mind this library is just a wrapper around the very active nodemailer: https://github.com/andris9/Nodemailer. All it really adds is a client pool, caching, and message templates.

**Comment by jplock** [comment]
The primary reason why I've been using node_mailer is the template support.  I'm not sure if the author of Nodemailer wants to add that or not directly into his tool, but that would solve my issues with this package.

**Comment by ghost** [comment]
Well, already switched to nodemailer.

**Pull request closed without merging**
